import type { IncidentCase } from "../data/incidents";
import type { AgentResult } from "./agent";
import { db } from "../backend/db";
import type { GateProposal } from "../backend/types";

/**
 * POSTMORTEM GENERATOR — the evidence chain writes the document.
 *
 * Every field below is derived from engine output (verdict, trace, memory)
 * or the audit ledger (gate decisions). Nothing is invented: if a fact is
 * unknown, the section says so. Same incident → same document.
 */

function shift(time: string, seconds: number): string {
  const [h, m, s] = time.split(":").map(Number);
  const t = (h * 3600 + m * 60 + s + seconds) % 86400;
  const p = (n: number) => String(n).padStart(2, "0");
  return `${p(Math.floor(t / 3600))}:${p(Math.floor((t % 3600) / 60))}:${p(t % 60)}`;
}

function actionItems(c: IncidentCase, a: AgentResult): string[] {
  const items: string[] = [];
  if (a.runbook.id !== "—") items.push(`Rehearse ${a.runbook.id} (${a.runbook.title}) in the next GameDay window`);
  if (c.signals.deploy) items.push(`Add a pre-deploy canary check for ${c.service} (triggered by ${c.signals.deploy})`);
  if (c.signals.corruption) items.push(`Add a synthetic corruption probe for ${c.service} — this incident was nearly invisible`);
  if (c.signals.drill) items.push(`Tag synthetic probe sources so drills self-declare (pre-approved rule D-1)`);
  if (c.memory) items.push(`Link ${c.memory.hits.join(", ")} as a related incident in the knowledge base`);
  if (c.signals.cacheHit !== undefined) items.push(`Alert on cache-hit ratio < 70% before origin burn becomes customer-visible`);
  if (c.signals.drift !== undefined) items.push(`Add model-drift alerting at ±10% (incident crossed ±15% before detection)`);
  if (items.length === 0) items.push(`Schedule a blameless review of ${c.id} with ${c.catalog.team}`);
  return items;
}

export function buildPostmortem(c: IncidentCase, a: AgentResult): string {
  const gates = db.read().gates as GateProposal[];
  const gate = gates.find((g) => g.caseId === c.id && g.status !== "pending");
  const s = c.signals;

  const timeline: string[] = [
    `- ${c.time} — alert received via ${c.source} (${c.service})`,
    `- ${shift(c.time, 2)} — agent triage complete: ${a.severity} → ${a.team}, confidence ${a.confidence.toFixed(2)} (${a.steps.length}-step trace)`,
  ];
  if (a.adjustment) timeline.push(`- ${shift(c.time, 2)} — critic pass: ${a.adjustment}`);
  if (a.page && gate) {
    timeline.push(
      `- ${gate.decidedAt ? gate.decidedAt.slice(11, 19) : shift(c.time, 160)} — page ${gate.status === "approved" ? "approved" : "REJECTED"} by ${gate.decidedBy ?? "reviewer"}${gate.reason ? ` — “${gate.reason}”` : ""} (ledger ${gate.id})`
    );
    if (gate.status === "approved") timeline.push(`- ${shift(c.time, 170)} — page delivered to ${a.team} on-call · acknowledged`);
  } else if (a.page) {
    timeline.push(`- — — page staged at human gate; no decision recorded in this sandbox yet`);
  } else {
    timeline.push(`- ${shift(c.time, 3)} — auto-resolved under pre-approved automation · audit note attached`);
  }
  timeline.push(`- ${shift(c.time, a.page ? 420 : 90)} — mitigated via ${a.runbook.id} · ${a.runbook.title}`);

  const impact = [
    `customers: ${s.customers === "none" ? "no customer surface" : s.customers}`,
    s.errorRate > 0 ? `error rate peaked at ${s.errorRate}%` : null,
    s.p99 ? `p99 ${s.p99}` : null,
    s.revenue ? "revenue was at risk" : null,
    s.corruption ? "silent data corruption — exports succeeded but arrived garbled" : null,
  ]
    .filter(Boolean)
    .join(" · ");

  const detection = a.steps
    .filter((st) => st.kind === "reason" || (st.kind === "verify" && st.status === "warn"))
    .map((st) => st.detail)
    .slice(0, 3);

  const lines = [
    `# Postmortem — ${c.id} · ${c.title}`,
    ``,
    `| | |`,
    `|---|---|`,
    `| **Severity** | ${a.severity} |`,
    `| **Owner** | ${a.team} (on-call: ${c.catalog.oncall}) |`,
    `| **Service** | ${c.service} · tier-${c.catalog.tier} · SLO ${c.catalog.slo} |`,
    `| **Runbook** | ${a.runbook.id} — ${a.runbook.title} (rev ${c.runbook.rev}) |`,
    `| **Status** | ${a.page ? (gate ? gate.status : "page pending human approval") : "resolved — pre-approved automation"} |`,
    `| **Generated by** | pagermind/postmortem v0.1 — deterministic: same evidence, same document |`,
    ``,
    `## Summary`,
    `${c.title}. The agent classified it ${a.severity} with confidence ${a.confidence.toFixed(2)} and routed it to ${a.team}. ${
      a.memoryNote ? `Incident memory contributed: ${a.memoryNote}.` : ""
    }`,
    ``,
    `## Timeline (sim clock)`,
    ...timeline,
    ``,
    `## Customer impact`,
    impact || "No customer impact identified.",
    ``,
    `## Detection`,
    ...detection.map((d) => `- ${d}`),
    a.evidence.length ? `` : ``,
    `## Recovery`,
    `Executed against ${a.runbook.id} (${a.runbook.title}). ${
      a.page && gate?.status === "approved"
        ? `The page was approved by ${gate.decidedBy} before firing — the decision is immutable in the audit ledger.`
        : a.page
        ? "The page required qualified human approval before firing."
        : "No page was required; the act was pre-approved, non-consequential automation."
    }`,
    ``,
    `## Action items`,
    ...actionItems(c, a).map((i) => `- [ ] ${i}`),
    ``,
    `## Evidence appendix (from the agent trace)`,
    ...a.evidence.map((e, i) => `${i + 1}. ${e}`),
    ``,
    `---`,
    `_Every statement above traces to a tool output, a fired rule, or a ledger entry. Fields the engine could not ground are marked as such._`,
  ];

  return lines.join("\n");
}
